In [ ]:
                  #logistic regression

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [28]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
df = pd.read_csv(url)

# Drop rows with any NaN values
df.dropna(inplace=True)

print(df.head())
print(df['species'].value_counts())

  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0
1  Adelie  Torgersen            39.5           17.4              186.0
2  Adelie  Torgersen            40.3           18.0              195.0
4  Adelie  Torgersen            36.7           19.3              193.0
5  Adelie  Torgersen            39.3           20.6              190.0

   body_mass_g     sex
0       3750.0    MALE
1       3800.0  FEMALE
2       3250.0  FEMALE
4       3450.0  FEMALE
5       3650.0    MALE
species
Adelie       146
Gentoo       119
Chinstrap     68
Name: count, dtype: int64

In [2]:
import pandas as pd
dataset=pd.DataFrame(df)
x = dataset

In [27]:
dataset = df.copy()

In [ ]:
pd.DataFrame

pandas.core.frame.DataFrame

In [5]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
#dependandt and independant feature
X = dataset
y = df.species

In [ ]:
y

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: object

In [ ]:
df['sex'].unique()

array(['MALE', 'FEMALE', nan], dtype=object)

In [ ]:
df.isnull().sum

<bound method DataFrame.sum of      species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0      False   False           False          False              False
1      False   False           False          False              False
2      False   False           False          False              False
3      False   False            True           True               True
4      False   False           False          False              False
..       ...     ...             ...            ...                ...
339    False   False            True           True               True
340    False   False           False          False              False
341    False   False           False          False              False
342    False   False           False          False              False
343    False   False           False          False              False

     body_mass_g    sex
0          False  False
1          False  False
2          False  False
3           True   True
4          False  False
..           ...    ...
339         True   True
340        False  False
341        False  False
342        False  False
343        False  False

[344 rows x 7 columns]>

In [ ]:
#to removie 'Adline' column
df[df['species']=='Adelie']

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,FEMALE
148,Adelie,Dream,36.0,17.8,195.0,3450.0,FEMALE
149,Adelie,Dream,37.8,18.1,193.0,3750.0,MALE
150,Adelie,Dream,36.0,17.1,187.0,3700.0,FEMALE
151,Adelie,Dream,41.5,18.5,201.0,4000.0,MALE

In [ ]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [ ]:
dataset.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
df.head(10)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: species, dtype: float64

In [ ]:
import pandas as pd

# Reload the original DataFrame as `df` has been overwritten
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
df = pd.read_csv(url)

# Correct the mapping keys from 'MAN'/'WOMEN' to 'MALE'/'FEMALE'
# .map() will return NaN for values not in the dictionary, which is appropriate for missing sex data.
df['sex'] = df['sex'].map({'MChinstrap':0,'Gentoo':1})

In [ ]:
df['species'] = df['species'].map({'MChinstrap':1,'Gentoo':0})

In [ ]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,NaN,Torgersen,39.1,18.7,181.0,3750.0,NaN
1,NaN,Torgersen,39.5,17.4,186.0,3800.0,NaN
2,NaN,Torgersen,40.3,18.0,195.0,3250.0,NaN
3,NaN,Torgersen,NaN,NaN,NaN,NaN,NaN
4,NaN,Torgersen,36.7,19.3,193.0,3450.0,NaN

In [ ]:
df.tail(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
334,NaN,Biscoe,46.2,14.1,217.0,4375.0,NaN
335,NaN,Biscoe,55.1,16.0,230.0,5850.0,NaN
336,NaN,Biscoe,44.5,15.7,217.0,4875.0,NaN
337,NaN,Biscoe,48.8,16.2,222.0,6000.0,NaN
338,NaN,Biscoe,47.2,13.7,214.0,4925.0,NaN
339,NaN,Biscoe,NaN,NaN,NaN,NaN,NaN
340,NaN,Biscoe,46.8,14.3,215.0,4850.0,NaN
341,NaN,Biscoe,50.4,15.7,222.0,5750.0,NaN
342,NaN,Biscoe,45.2,14.8,212.0,5200.0,NaN
343,NaN,Biscoe,49.9,16.1,213.0,5400.0,NaN

In [6]:
df.isnull()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
339,False,False,True,True,True,True,True
340,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False

In [7]:
df.dropna()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [8]:
df.drop_duplicates()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [9]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [10]:
df.dtypes

species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

In [29]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])
df['island'] = le.fit_transform(df['island'])
df['sex'] = le.fit_transform(df['sex'])

In [13]:
 df['species'].dtype

dtype('int64')

In [17]:
df.dtypes

species                int64
island                 int64
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                    int64
dtype: object

In [30]:
X = df.drop('species', axis=1)  # Independent features
y = df['species']               # Dependent feature

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [32]:
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()

x_train=Scaler.fit_transform(X_train)
X_test=Scaler.transform(X_test)

In [33]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [40]:
from sklearn.model_selection import cross_val_score

# Using accuracy as a scoring metric for classification
# The model object is named 'model', not 'regression'
scores = cross_val_score(model, x_train, y_train, scoring='accuracy', cv=5)

print(f"Cross-validation Accuracy Scores: {scores}")
print(f"Mean Cross-validation Accuracy: {scores.mean():.4f}")

Cross-validation Accuracy Scores: [1.         1.         0.98113208 0.98113208 1.        ]
Mean Cross-validation Accuracy: 0.9925

In [42]:
from sklearn.metrics import r2_score, mean_absolute_error

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R² Score:", r2)
print("Mean Absolute Error:", mae)

R² Score: 1.0
Mean Absolute Error: 0.0

In [39]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

Model Accuracy: 1.0000